LoadingError: condense SvgHasNoElements and RootElementIsNotSvg into NoSvgRoot
It turns out that libxml2 doesn't seem to allow documents without a
single element, so the first case may be moot.  The code covers both
possibilities with a single variant now.