Update vulnerable crates
Crate:         smallvec
Version:       0.6.0
Title:         Possible double free during unwinding in SmallVec::insert_many
Date:          2018-07-19
ID:            RUSTSEC-2018-0003
URL:           https://rustsec.org/advisories/RUSTSEC-2018-0003
Solution:      Upgrade to >=0.6.3 OR >=0.3.4, <0.4.0 OR >=0.4.5, <0.5.0 OR >=0.5.1, <0.6.0
Dependency tree:
smallvec 0.6.0
└── cssparser 0.23.2
    └── rsvg_internals 0.0.1

Crate:         smallvec
Version:       0.6.0
Warning:       yanked

error: 1 vulnerability found!
warning: 1 allowed warning found