text: Add explicit lifetime to an impl block
While building with rustc <= 1.31 the following error would occur.

error[E0106]: missing lifetime specifier
   --> rsvg_internals/src/text.rs:794:11
    |
794 | impl From<&XmlLang> for pango::Language {
    |           ^ expected lifetime parameter

error: aborting due to previous error

The lifetime is not required with rustc 1.31+ and can be omitted,
but we still need to support older versions for the time being.