Fix generating Vala bindings in non-srcdir builds
The location of the files vapigen uses must be relative to the source
and build directories, otherwise they will not be found.

This fixes the librsvg build in Continuous, which is failing with the
error:

/usr/bin/vapigen-0.40  --library librsvg-2.0 --metadatadir .. --pkg gio-2.0 --pkg cairo Rsvg-2.0.gir Rsvg-2.0-custom.vala
error: Rsvg-2.0-custom.vala not found
Generation failed: 1 error(s), 0 warning(s)

Signed-off-by: Emmanuele Bassi <ebassi@gnome.org>