Fix generation of test coverage data for the C API code in librsvg-c
Don't use meson's coverage option; use clang's options directly.

We explicitly do not use meson's -Db_coverage=true option anymore.
That option causes meson to add --coverage to clang's options, which
makes it use GCC-compatible gcov output.  Instead, we use the clang
options -fprofile-instr-generate -fcoverage-mapping, per
https://clang.llvm.org/docs/SourceBasedCodeCoverage.html

Somehow, if we use GCC-compatible gcov output (via meson's
-Db_coverage=true), the profile data
for librsvg-c is not captured when grcov calls llvm-cov internally:
running grcov with --log-level=TRACE shows a bunch of these:

  23:19:58 [WARN] Suppressing error returned by llvm-cov tool for binary "./_build/librsvg-c/tests-c/api.p/api.c.o"

  Failure while running
  "/usr/local/rustup/toolchains/1.92.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-cov"
  "export" "./_build/librsvg-c/tests-c/api.p/api.c.o" "--instr-profile"
  "/tmp/.tmplXtaUD/0/grcov.profdata" "--format" "lcov"

  error: failed to load coverage: './_build/librsvg-c/tests-c/api.p/api.c.o': no coverage data found
  error: could not load coverage information

Using clang's options explicitly via CFLAGS causes this to work
correctly.

Part-of: <https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/1207>