Temporarily allow the msvc job to fail so we can merge all the meson-related MRs
Tests are failing like this:

     Running tests\text.rs (target\release\deps\text-89aa61eda7b06d51.exe)
(process:6716): Pango-WARNING **: 10:18:35.649: couldn't load font "Ahem Not-Rotated 50", falling back to "Sans Not-Rotated 50", expect ugly output.
(process:6716): Pango-WARNING **: 10:18:35.649: couldn't load font "Ahem Not-Rotated 5", falling back to "Sans Not-Rotated 5", expect ugly output.
(process:6716): Pango-WARNING **: 10:18:35.664: couldn't load font "Ahem Not-Rotated 20", falling back to "Sans Not-Rotated 20", expect ugly output.
error: test failed, to rerun pass `-p librsvg --test text`