Remove deny(warnings) from the toplevel src/lib.rs
This got moved from librsvg_crate/src/lib.rs, where it was presumably
because we didn't want warnings in the public API crate.  Now that
we have a single crate, however, this can create warnings on
architectures which we don't test in the CI.

Specifically, this was causing this warning-as-error in
gnome-build-meta for aarch64:

        ======================================================================
        345 | |         rsvg_pixbuf_from_file_at_max_size => ptr::null_mut();
        346 | |
        347 | |         !filename.is_null(),
        348 | |         max_width >= 1 && max_height >= 1,
        349 | |         error.is_null() || (*error).is_null(),
        350 | |     }
            | |_____- in this macro invocation
            |
            = help: cast can be replaced by coercion; this might require a temporary variable
            = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
        error: trivial cast: `*const u8` as `*const u8`
           --> src/c_api/messages.rs:112:21
            |
        112 |                       concat!(stringify!($func_name), "\0").as_ptr() as *const _,
            |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            |
           ::: src/c_api/pixbuf_utils.rs:344:5
            |
        344 | /     rsvg_return_val_if_fail! {
        345 | |         rsvg_pixbuf_from_file_at_max_size => ptr::null_mut();
        346 | |
        347 | |         !filename.is_null(),
        348 | |         max_width >= 1 && max_height >= 1,
        349 | |         error.is_null() || (*error).is_null(),
        350 | |     }
            | |_____- in this macro invocation