NodeError: use a String for the attr_name, not a &'static str
For now, we'll need to keep around attr_names that come from the C
code.  We don't know if the pointers we are passed are to
statically-allocated strings or not, so we'll just use full Strings on
the heap for NodeError.