rsvg_internals: update nalgebra to a newer minor version
The previous version was not compilling with rustc 1.40

error[E0502]: cannot borrow `*self` as immutable because it is also borrowed as mutable
   --> /home/alatiera/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.16.4/src/base/cg.rs:292:44
    |
292 |                 self[(j, i)] += shift[j] * self[(D::dim() - 1, i)];
    |                 ---------------------------^^^^-------------------
    |                 |                          |
    |                 |                          immutable borrow occurs here
    |                 mutable borrow occurs here
    |                 mutable borrow later used here

error: aborting due to previous error

Although you should rather be using the 2.46 branch of librsvg as 2.44 is EOL.